/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Completions */
        get: operations["completions_api_completions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/completions/{completion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Completion */
        get: operations["completion_api_completions__completion_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest */
        post: operations["ingest_api_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshot */
        get: operations["snapshot_api_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdapterStatus */
        AdapterStatus: {
            /** Error */
            error?: string | null;
            /**
             * Gaps
             * @default []
             */
            gaps: string[];
            /**
             * Harness
             * @enum {string}
             */
            harness: "claude" | "codex" | "hermes";
            /** Ok */
            ok: boolean;
        };
        /** CompletionDetail */
        CompletionDetail: {
            /** Completed At */
            completed_at: number;
            /** Excerpt */
            excerpt: string;
            /**
             * Harness
             * @enum {string}
             */
            harness: "claude" | "codex" | "hermes";
            /** Id */
            id: number;
            /** Machine Id */
            machine_id: string;
            /** Project Id */
            project_id: string | null;
            /** Response */
            response: string;
            /** Session Id */
            session_id: string;
            /** Title */
            title: string | null;
        };
        /**
         * CompletionObs
         * @description A settled response cycle with its delivered final response.
         */
        CompletionObs: {
            /** Completed At */
            completed_at: number;
            /** Cwd */
            cwd?: string | null;
            /**
             * Harness
             * @enum {string}
             */
            harness: "claude" | "codex" | "hermes";
            project?: components["schemas"]["ProjectRef"] | null;
            /** Request Id */
            request_id: string;
            /** Response */
            response: string;
            /** Session Id */
            session_id: string;
            /** Title */
            title?: string | null;
        };
        /** CompletionPage */
        CompletionPage: {
            /** Items */
            items: components["schemas"]["CompletionSummary"][];
            /** Total */
            total: number;
        };
        /** CompletionSummary */
        CompletionSummary: {
            /** Completed At */
            completed_at: number;
            /** Excerpt */
            excerpt: string;
            /**
             * Harness
             * @enum {string}
             */
            harness: "claude" | "codex" | "hermes";
            /** Id */
            id: number;
            /** Machine Id */
            machine_id: string;
            /** Project Id */
            project_id: string | null;
            /** Session Id */
            session_id: string;
            /** Title */
            title: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MachineView */
        MachineView: {
            /** Adapters */
            adapters: components["schemas"]["AdapterStatus"][];
            /** Expired Pending */
            expired_pending: number;
            /** Id */
            id: string;
            /** Last Seen */
            last_seen: number;
            /** Name */
            name: string;
            /** Stale */
            stale: boolean;
        };
        /** ProjectRef */
        ProjectRef: {
            /** Checkout */
            checkout: string;
            /** Keys */
            keys: string[];
            /** Name */
            name: string;
        };
        /** ProjectView */
        ProjectView: {
            /** Detail */
            detail: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * Report
         * @description One collector upload: a full current snapshot plus queued completions.
         */
        Report: {
            /** Adapters */
            adapters: components["schemas"]["AdapterStatus"][];
            /**
             * Completions
             * @default []
             */
            completions: components["schemas"]["CompletionObs"][];
            /**
             * Expired Total
             * @default 0
             */
            expired_total: number;
            /** Machine Id */
            machine_id: string;
            /** Machine Name */
            machine_name: string;
            /** Sent At */
            sent_at: number;
            /** Sessions */
            sessions: components["schemas"]["SessionObs"][];
        };
        /** ReportAck */
        ReportAck: {
            /** Accepted */
            accepted: number;
        };
        /** SessionObs */
        SessionObs: {
            /** Activity */
            activity?: string | null;
            /** Cwd */
            cwd?: string | null;
            /** Gap */
            gap?: string | null;
            /**
             * Harness
             * @enum {string}
             */
            harness: "claude" | "codex" | "hermes";
            /** Observed At */
            observed_at: number;
            /** Parent Id */
            parent_id?: string | null;
            project?: components["schemas"]["ProjectRef"] | null;
            /** Request Id */
            request_id?: string | null;
            /** Session Id */
            session_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "working" | "waiting" | "idle" | "unknown";
            /** Title */
            title?: string | null;
        };
        /** SessionView */
        SessionView: {
            /** Activity */
            activity: string | null;
            /** Checkout */
            checkout: string | null;
            /** Gap */
            gap: string | null;
            /**
             * Harness
             * @enum {string}
             */
            harness: "claude" | "codex" | "hermes";
            /**
             * Helpers
             * @default []
             */
            helpers: components["schemas"]["SessionView"][];
            /** Key */
            key: string;
            /** Machine Id */
            machine_id: string;
            /** Observed At */
            observed_at: number;
            /** Project Id */
            project_id: string | null;
            /** Session Id */
            session_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "working" | "waiting" | "idle" | "unknown";
            /** Title */
            title: string | null;
        };
        /** Snapshot */
        Snapshot: {
            /** Machines */
            machines: components["schemas"]["MachineView"][];
            /** Projects */
            projects: components["schemas"]["ProjectView"][];
            /** Server Time */
            server_time: number;
            /** Sessions */
            sessions: components["schemas"]["SessionView"][];
            /** Stale After */
            stale_after: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    completions_api_completions_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    completion_api_completions__completion_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                completion_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    ingest_api_ingest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Report"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportAck"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshot_api_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Snapshot"];
                };
            };
        };
    };
}
